### ISSUE TITLE
nproc_per_node参数为2会报错Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.

### ISSUE THREAD

**Issue by AI-Study-Han** [unconv/llama2-flask-api#1]

**Comment by unconv** [comment]
Run `./run_api.sh HOST PORT` to run it on a different port. For example `./run_api.sh 127.0.0.1 5151` to run it on the port 5151. Use `0.0.0.0` as the host if you want it to be accessible over the internet.

**Comment by unconv** [comment]
Sorry, it seems like this is the same issue as #2 (the API did not work with the larger models). I have updated the code to work with the larger models now. Please let me know if it works for you now

**Comment by unconv** [comment]
Based on #2 this seems to be solved.
