### ISSUE TITLE
Port in use error

### ISSUE THREAD

**Issue by firslov** [unconv/llama2-flask-api#2]
* Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:6667
 * Running on http://192.168.3.13:6667
Press CTRL+C to quit
Address already in use
Port 6667 is in use by another program. Either identify and stop that program, or start the server with a different port.
---
No matter which port I use, still get this error.

**Comment by unconv** [comment]
Can you share the command you ran to start the API and what the output was? This is the expected output:

```shell
$ ./run_api.sh 0.0.0.0 6667
Starting Llama 2 Flask API...
Model: 7b-chat

> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Loaded in 14.67 seconds
 * Serving Flask app 'api'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:6667
 * Running on http://172.31.36.1:6667
Press CTRL+C to quit
```

Also what system are you running it on?

**Comment by firslov** [comment]
@unconv Sure, my opereation system is Ubuntu18.04, the command and output is

```
$ ./run_api.sh 0.0.0.0 666
Starting Llama 2 Flask API...
Model: /workspace/llama2/Llama-2-13b-chat-pth

WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application
as needed.
*****************************************
> initializing model parallel with size 2
> initializing ddp with size 1
> initializing pipeline with size 1
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:666
 * Running on http://172.17.0.2:666
Press CTRL+C to quit
Loaded in 19.38 seconds
 * Serving Flask app 'api'
 * Debug mode: off
Address already in use
Port 666 is in use by another program. Either identify and stop that program, or start the server with a different port.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 83805 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 83782) of binary: /home/jd@422/.conda/envs/LLaMA/bin/python3
```

**Comment by unconv** [comment]
First of all, it says `Model: /workspace/llama2/Llama-2-13b-chat-pth` in the output, but you didn't pass in the command line argument for the model. Therefore it should say `Model: 7b-chat` which is the default in `run_api.sh`. So I'm guessing you changed the original code.

Secondly, I haven't tested it with Llama 13B, because I haven't gotten it to work (even the examples by Meta). Make sure you can get the Meta example code to run first, before testing the API.

Also, I think you need to set `--nproc_per_node` to `2` with the 13B model and `8` for 70B. But again, I haven't gotten them to work myself. Only 7B

**Comment by unconv** [comment]
Also, if you are able to run the `example_chat_completion.py` by Meta with their example `torchrun` command, then you can just replace `example_chat_completion.py` with `api.py` from this repo and it should work.

**Comment by firslov** [comment]
Yes, I changed the `run_api.sh`, and ensured the argumets were correct. I have already set the `--nproc_per_node` to 2 and `example_chat_completion.py` worked well. 

I guess the problem may be related to `FastAPI`?

**Comment by unconv** [comment]
I think `--nproc_per_node` is running the `api.py` file multiple times and that causes the issue. So I have to rethink how to create the whole API lol. It will only work on 7B (have you tried it?)

**Comment by firslov** [comment]
~I googled it, and indeed, `--nproc_per_node` does not place the model on two GPUs but instead runs two separate models on two GPUs individually.~
---
sorry, it seems that's not the case. It should be `--nproc_per_node` causing FastAPI to run twice.

**Comment by unconv** [comment]
I just updated (basically rewrote) the code to work with the larger models. Didn't try with 70B yet, but 13B works.

Just run `./api.py --model 13b-chat` (or `./api.py --ckpt_dir /workspace/llama2/Llama-2-13b-chat-pth` if your model is in a custom location). It will detect `nproc_per_node` automatically.

Let me know if it works for you

**Comment by firslov** [comment]
It looks good. You manually implemented multi-process communication. I made some modifications to the previous code, using `dist.broadcast_object_list()` can also achieve parallel inference.

**Comment by firslov** [comment]
I have tested the new code, and it successfully runs on the 13B model.

**Comment by unconv** [comment]
Great! Thanks for letting me know. This was my first project with multiprocessing, pytorch and multiprocessing in pytorch haha. Learned most of it from GPT-4. I'll check out `dist.broadcast_object_list()`
