### ISSUE TITLE
Want a service with a public API

### ISSUE THREAD

**Issue by Nerva05251228** [unconv/llama2-flask-api#3]
Hello!
I have successfully built a service for llama2 on the cloud, and there is a public URL that can access the webui interface of llama2. However, at this time, I hope to enable other computers (some computers with poor configuration) to access it through a public API. How can I use your project to do such an operation? I tried some methods, but they all opened a local port and did not provide external services.
Thank you so much!

**Comment by unconv** [comment]
You need to run the API with `--host 0.0.0.0` to make the API endpoint accessible publicly:

```console
$ ./api.py --host 0.0.0.0
```

You can also set a specific port with the `--port` flag.

Note that there is no authentication in this API so you would have to implement that yourself. Otherwise the API is open to everyone.

**Comment by Nerva05251228** [comment]
> You need to run the API with `--host 0.0.0.0` to make the API endpoint accessible publicly:您需要运行 API 才能 `--host 0.0.0.0` 使 API 终端节点可公开访问：
> 
> ```
> $ ./api.py --host 0.0.0.0
> ```
> 
> You can also set a specific port with the `--port` flag.您还可以使用 `--port` 标志设置特定端口。
> 
> Note that there is no authentication in this API so you would have to implement that yourself. Otherwise the API is open to everyone.请注意，此 API 中没有身份验证，因此您必须自己实现。否则，API 对所有人开放。

Thanks for your reply! I would have a try!

**Comment by Nerva05251228** [comment]
> You need to run the API with `--host 0.0.0.0` to make the API endpoint accessible publicly:
> 
> ```
> $ ./api.py --host 0.0.0.0
> ```
> 
> You can also set a specific port with the `--port` flag.
> 
> Note that there is no authentication in this API so you would have to implement that yourself. Otherwise the API is open to everyone.

I ran Python api.py -- host 0.0.0.0
The output is as follows:

Initializing Llama 2...
Model: llama-2-7b-chat

> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Loaded in 8.08 seconds

Starting Flask API...
 * Serving Flask app 'api'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:6006
 * Running on http://172.17.0.2:6006
Press CTRL+C to quit
127.0.0.1 - - [16/Aug/2023 15:50:03] "GET / HTTP/1.1" 404 -

But how should I call the API interface? I tried to open 127.0.0.1:6006 locally and found it to be a 404 webpage, while 172.17.0.2:6006 kept rotating. What testing code should I write for testing?

**Comment by Nerva05251228** [comment]
> > You need to run the API with `--host 0.0.0.0` to make the API endpoint accessible publicly:
> > ```
> > $ ./api.py --host 0.0.0.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can also set a specific port with the `--port` flag.
> > Note that there is no authentication in this API so you would have to implement that yourself. Otherwise the API is open to everyone.
> 
> I ran Python api.py -- host 0.0.0.0 The output is as follows:
> 
> Initializing Llama 2... Model: llama-2-7b-chat
> 
> > initializing model parallel with size 1
> > initializing ddp with size 1
> > initializing pipeline with size 1
> > Loaded in 8.08 seconds
> 
> Starting Flask API...
> 
> * Serving Flask app 'api'
> * Debug mode: off
>   WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
> * Running on all addresses (0.0.0.0)
> * Running on http://127.0.0.1:6006
> * Running on http://172.17.0.2:6006
>   Press CTRL+C to quit
>   127.0.0.1 - - [16/Aug/2023 15:50:03] "GET / HTTP/1.1" 404 -
> 
> But how should I call the API interface? I tried to open 127.0.0.1:6006 locally and found it to be a 404 webpage, while 172.17.0.2:6006 kept rotating. What testing code should I write for testing?

I have fixed this issue! Thank you very much!
